# Generated by Django 3.0.2 on 2020-01-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191217_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='restrict_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
